<?php if(time() > 1430145091){return array();} return array (
  'https_port' => '443',
  'http_host' => 'mexicotruckload.com.mx',
  'database_type' => 'mysql',
  'database_server' => 'localhost',
  'database_connection_charset' => 'utf8',
  'database_charset' => 'utf8',
  'dbase' => 'mexicotr_sitex',
  'database_user' => 'mexicotr_sitex',
  'database_password' => 'W5OQ%~9S_4(W',
  'table_prefix' => 'modx_',
  'site_sessionname' => 'SN5447bc110fdfe',
  'cache_disabled' => 'false',
  'inplace' => 0,
  'unpacked' => '1',
  'config_options' => 
  array (
  ),
  'driver_options' => 
  array (
  ),
  'context_web_path' => '/home/projects/public_html/truckload/platform/',
  'context_web_url' => '/truckload/platform/',
  'context_mgr_path' => '/home/projects/public_html/truckload/platform/manager/',
  'context_mgr_url' => '/truckload/platform/manager/',
  'context_connectors_path' => '/home/projects/public_html/truckload/platform/connectors/',
  'context_connectors_url' => '/truckload/platform/connectors/',
  'core_path' => '/home/mexicotr/public_html/core/',
  'web_path' => '/home/projects/public_html/truckload/platform/',
  'web_url' => '/truckload/platform/',
  'mgr_path' => '/home/projects/public_html/truckload/platform/manager/',
  'mgr_url' => '/truckload/platform/manager/',
  'connectors_path' => '/home/projects/public_html/truckload/platform/connectors/',
  'connectors_url' => '/truckload/platform/connectors/',
  'web_path_auto' => 0,
  'web_url_auto' => 0,
  'mgr_path_auto' => 0,
  'mgr_url_auto' => 0,
  'connectors_path_auto' => 0,
  'connectors_url_auto' => 0,
  'processors_path' => '/home/mexicotr/public_html/core/model/modx/processors/',
  'assets_path' => '/home/projects/public_html/truckload/platform/assets/',
  'assets_url' => '/truckload/platform/assets/',
  'database_dsn' => 'mysql:host=localhost;dbname=mexicotr_sitex;charset=utf8',
  'language' => 'en',
  'server_dsn' => 'mysql:host=localhost;charset=utf8',
  'installmode' => 3,
  'database' => 'mexicotr_sitex',
  'database_collation' => 'utf8_unicode_ci',
);